from typing import Union,Any
from log import Log

class ServerError:
    def __init__(self, message: Any):...

class ErrorHandler:
    def __init__(
        self, err, src: str, 
        logger: Union[Log,None] = None, 
        level: int = 1,
        exit=False, wait=False
        ):...
    def show(self, message: Any) -> None:...
    def getStack(self) -> str:...
    def quit(self) -> None:...
    def __call__(self) -> None:...
