name: Build execute file

on: [release]

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      ylogin: ${{ secrets.LANZOU_ID }}
      phpdisk_info: ${{ secrets.LANZOU_PSD }}
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.10
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        pip install nuitka
        pip install -r requirements.txt
    - name: build
      run: |
        nuitka --follow-impnuitka --follow-imports --noinclude-IPython-mode=nofollow --standalone --include-data-file="grapheme_break_property.json"=grapheme\data\  --include-data-file=fail.mp3=fail.mp3 --onefile main.py
    - name: upload
      uses: actions/upload-artifact@v3.0.0
      with:
        path: main.exe
        if-no-files-found: error
    - name: upload to lanzou
      run: |
        python3 .github/script/lzy.py
    
