name: Build execute file

on: [release]

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      ylogin: ${{ secrets.LANZOU_ID }}
      phpdisk_info: ${{ secrets.LANZOU_PSD }}
    strategy:
      max-parallel: 5

    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip' # caching pip dependencies
    - name: Install dependencies
      run: |
        pip install pyinstaller
        pip install -r requirements.txt
    - name: build
      run: |
        pyinstaller -F --add-data fail.mp3:. --disable-windowed-traceback -c main.py
    - name: upload
      uses: actions/upload-artifact@v3.0.0
      with:
        path: main.exe
        if-no-files-found: error
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: main.exe

